module.exports.SUCCESS = 'SUCCESS';

module.exports.VALIDATION_ERROR = 'VALIDATION_ERROR';
module.exports.INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
module.exports.AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';

module.exports.SUCCESS = 'SUCCESS';